---
- name: Pull docker image of Calculator
  hosts: remoteserver
  remote_user: azureuser
  tasks:
    - name: Pull Calculator image
      docker_image:
        name: ebad95/devops
        source: pull
